from .alphabeta import GMK_AlphaBetaPlayer
from .human import GMK_HumanPlayer
from .mcts_v1 import GMK_NaiveMTCS
from .mcts_v2 import GMK_BetterMTCS
from .mcts_v3 import GMK_AlphaGoMTCS
from .qlearning_v1 import GMK_TabularQPlayer
from .qlearning_v2 import GMK_ApproximateQPlayer
from .bots.beginner import GMK_Beginner
from .bots.master import GMK_Master
from .bots.intermediate import GMK_Intermediate
from .bots.advanced import GMK_Advanced
